# Generated by Django 4.1.7 on 2023-03-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='is_auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
