# Generated by Django 4.1.7 on 2023-03-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_control', '0001_initial'),
        ('group_control', '0002_alter_groupmodel_is_auto_accept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='cover_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_picture', to='utility_control.filemodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_picture', to='utility_control.filemodel'),
        ),
    ]
