# Generated by Django 4.1.7 on 2023-03-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0003_alter_groupmodel_cover_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostclapmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouppostcommentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouppostmodel',
            name='user',
        ),
    ]
